BASE_TASK_CONFIG_PATH: "configs/tasks/eqa_mp3d.yaml"
TRAINER_NAME: "eqa-cnn-pretrain"

ENV_NAME: "EQACNNPretrainILEnv"
SIMULATOR_GPU_ID: 0
TORCH_GPU_ID: 0

DATASET_PATH: "data/datasets/eqa/eqa_cnn_pretrain/{split}/{split}.db"

EVAL_CKPT_PATH_DIR: "data/eqa/eqa_cnn_pretrain/checkpoints/resnet101/epoch_5.ckpt"

CHECKPOINT_FOLDER: "data/eqa/eqa_cnn_pretrain/checkpoints/resnet101"
TENSORBOARD_DIR: "data/eqa/eqa_cnn_pretrain/tb/resnet101"
RESULTS_DIR: "data/eqa/eqa_cnn_pretrain/results/resnet101/{split}/{type}"
OUTPUT_LOG_DIR: data/eqa/eqa_cnn_pretrain/logs

LOG_METRICS: True
LOG_INTERVAL: 50
EVAL_SAVE_RESULTS: True
EVAL_SAVE_RESULTS_INTERVAL: 50
# Force PyTorch to be single threaded as
# this improves performance considerably
FORCE_TORCH_SINGLE_THREADED: True

# TODO: change model name, unet-resnet101
IL:
  EQACNNPretrain:
    # params
    max_epochs: 300
    batch_size: 20
    lr: 1e-5
    model: "resnet101" # "resnet101" or "multitask_cnn" are supported for now
